language: node_js
node_js:
- 10
notifications:
  email: false
  slack:
    secure: MuvEJ5Wnvz0FjgzhbWyqMwWi4lU3ORGyEC30co9seaPibn3T6uyYEntyF0jocdAe7ivyTvfynj5Yb8Zuqw6PLpSwDK3N0ayZ66oaWC3baH1F5b9jEuO7Xo/zCdKzXFFEdwjxMwP8ap2wisPb98pPC2RMSLosBQghMgnYOzPfEM5mk25zmLuZr3wfLES/lOxlKCR9lI6nJ6whdb6Jf4QQvrK9bopS17RerS+fhObuWZzVE4m8UjZExYa/p9nr3uLIAhlMmNqNifz0BBI+XGx8XzVE+p98oGdBM387aCdinvWbBIvplAFl5y7t2ilfDw6mGBCzQBfJXp2Fq39V49qiQkpCGuRVHtCUBqC5c7gt8nLSMipDS86uAgjwFj9OFMN9uVUaCLUknvnUPNWn9vKHLyWvwXDeHmAwJFmAXRwXlMqu2CSAv6LIFXzKvwM5brwHUFiPkuwte0Oxb7U4l3CRM+HaZamkJOYzVBPkGBecOydRyySfAfJHMgYGjE+dFthBrdjUlpmcoCShEsVLM8eSsrKXOvW9KSGkI9Q6h/hRw2v9bMD2PpDe+KJX8kFWsL6MYO2/4TOrYdmeA8B35EAIVbaAAOKvFVAfG61OSnWpvXcgEBQRZQNj2ZnF1O+tMZsxeEINApo3ZWdNoDamPs2CbbGcEm1m7vnp6B8=
cache: yarn
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
